### ISSUE TITLE
focus should be focus-visible

### ISSUE THREAD

**Issue by steida** [soorria/tailwindcss-hocus#1]
The problem with focus is that it reacts on the mouse, which should not.

https://tailwindcss.com/docs/hover-focus-and-other-states#focus-visible

```ts
plugin(function ({ addVariant }) {
  addVariant("hocus", ["&:hover", "&:focus-visible"]);
  addVariant("group-hocus", [
    ":merge(.group):hover &",
    ":merge(.group):focus-visible &",
  ]);
}),
```

**Comment by soorria** [comment]
Ah yep, I've been thinking about this - I'll probably end up add extra variants (`hocus-visible`, `group-hocus-visible` to match base Tailwind.
